// This file has been generated by the reflectable package.
// https://github.com/dart-lang/reflectable.

import 'dart:core';

import 'package:pomotimer/common/reflector.dart' as prefix0;
import 'package:pomotimer/states/timer_states.dart' as prefix1;
// ignore_for_file: camel_case_types
// ignore_for_file: implementation_imports
// ignore_for_file: prefer_adjacent_string_concatenation
// ignore_for_file: prefer_collection_literals
// ignore_for_file: unnecessary_const
// ignore_for_file: unused_import

import 'package:reflectable/mirrors.dart' as m;
import 'package:reflectable/reflectable.dart' as r show Reflectable;
import 'package:reflectable/src/reflectable_builder_based.dart' as r;

final _data = <r.Reflectable, r.ReflectorData>{
  const prefix0.Reflector(): r.ReflectorData(
      <m.TypeMirror>[
        r.NonGenericClassMirrorImpl(
            r'TimerStates',
            r'.TimerStates',
            134217735,
            0,
            const prefix0.Reflector(),
            const <int>[-1],
            null,
            null,
            -1,
            {r'loadFromStorage': () => prefix1.TimerStates.loadFromStorage},
            {},
            {
              r'': (bool b) => (
                      {timerRunning,
                      startTime,
                      customFocusTime,
                      customShortBreakTime,
                      customLongBreakTime,
                      reminderType}) =>
                  b
                      ? prefix1.TimerStates(
                          customFocusTime: customFocusTime,
                          customLongBreakTime: customLongBreakTime,
                          customShortBreakTime: customShortBreakTime,
                          reminderType: reminderType,
                          startTime: startTime,
                          timerRunning: timerRunning)
                      : null,
              r'fromJson': (bool b) =>
                  (json) => b ? prefix1.TimerStates.fromJson(json) : null,
              r'fromJsonText': (bool b) =>
                  (json) => b ? prefix1.TimerStates.fromJsonText(json) : null
            },
            -1,
            -1,
            const <int>[-1],
            null,
            {
              r'==': 2,
              r'toString': 0,
              r'noSuchMethod': 2,
              r'hashCode': 0,
              r'runtimeType': 0,
              r'addListener': 2,
              r'removeListener': 2,
              r'dispose': 0,
              r'notifyListeners': 1,
              r'hasListeners': 0,
              r'toJson': 0,
              r'toJsonText': 0,
              r'timerRunning': 0,
              r'timerRunning=': 2,
              r'startTime': 0,
              r'startTime=': 2,
              r'offsetTime': 0,
              r'offsetTime=': 2,
              r'pausing': 0,
              r'pausing=': 2,
              r'startPauseTime': 0,
              r'startPauseTime=': 2,
              r'customFocusTime': 0,
              r'customFocusTime=': 2,
              r'customShortBreakTime': 0,
              r'customShortBreakTime=': 2,
              r'customLongBreakTime': 0,
              r'customLongBreakTime=': 2,
              r'reminderType': 0,
              r'reminderType=': 2,
              r'customTimes': 0,
              r'loadFromStorage': 0
            })
      ],
      null,
      null,
      <Type>[prefix1.TimerStates],
      1,
      {
        r'==': (dynamic instance) => (x) => instance == x,
        r'toString': (dynamic instance) => instance.toString,
        r'noSuchMethod': (dynamic instance) => instance.noSuchMethod,
        r'hashCode': (dynamic instance) => instance.hashCode,
        r'runtimeType': (dynamic instance) => instance.runtimeType,
        r'addListener': (dynamic instance) => instance.addListener,
        r'removeListener': (dynamic instance) => instance.removeListener,
        r'dispose': (dynamic instance) => instance.dispose,
        r'notifyListeners': (dynamic instance) => instance.notifyListeners,
        r'hasListeners': (dynamic instance) => instance.hasListeners,
        r'toJson': (dynamic instance) => instance.toJson,
        r'toJsonText': (dynamic instance) => instance.toJsonText,
        r'timerRunning': (dynamic instance) => instance.timerRunning,
        r'startTime': (dynamic instance) => instance.startTime,
        r'offsetTime': (dynamic instance) => instance.offsetTime,
        r'pausing': (dynamic instance) => instance.pausing,
        r'startPauseTime': (dynamic instance) => instance.startPauseTime,
        r'customFocusTime': (dynamic instance) => instance.customFocusTime,
        r'customShortBreakTime': (dynamic instance) =>
            instance.customShortBreakTime,
        r'customLongBreakTime': (dynamic instance) =>
            instance.customLongBreakTime,
        r'reminderType': (dynamic instance) => instance.reminderType,
        r'customTimes': (dynamic instance) => instance.customTimes
      },
      {
        r'timerRunning=': (dynamic instance, value) =>
            instance.timerRunning = value,
        r'startTime=': (dynamic instance, value) => instance.startTime = value,
        r'offsetTime=': (dynamic instance, value) =>
            instance.offsetTime = value,
        r'pausing=': (dynamic instance, value) => instance.pausing = value,
        r'startPauseTime=': (dynamic instance, value) =>
            instance.startPauseTime = value,
        r'customFocusTime=': (dynamic instance, value) =>
            instance.customFocusTime = value,
        r'customShortBreakTime=': (dynamic instance, value) =>
            instance.customShortBreakTime = value,
        r'customLongBreakTime=': (dynamic instance, value) =>
            instance.customLongBreakTime = value,
        r'reminderType=': (dynamic instance, value) =>
            instance.reminderType = value
      },
      null,
      [
        const [0, 0, null],
        const [
          0,
          0,
          const [#saveToStorage]
        ],
        const [1, 0, null],
        const [
          0,
          0,
          const [
            #timerRunning,
            #startTime,
            #customFocusTime,
            #customShortBreakTime,
            #customLongBreakTime,
            #reminderType
          ]
        ]
      ])
};

final _memberSymbolMap = null;

void initializeReflectable() {
  r.data = _data;
  r.memberSymbolMap = _memberSymbolMap;
}
